### ISSUE TITLE
是否是环链表，采用快慢指针，一个走的快些一个走的慢些 如果最终相遇了就说明是环，貌似并不是最优解

### ISSUE THREAD

**Issue by dk-lockdown** [crossoverJie/JCSprout#104]
也许和你的数据结构有关，如果你的链表保存了链表的length,可以遍历一遍，没遍历一个元素，size加一，size大于length的时候，即有环，只需遍历length+1次。如果采取快慢指针，大概率需要循环1.5length以上次数

**Comment by crossoverJie** [comment]
@dk-lockdown 可以按照这个思路提个 `PR`。

**Comment by ostreamBaba** [comment]
有环的东西还能知道长度?? 想知道长度你还不得要先知道环的入口在哪里，还是得利用快慢指针模拟一遍。
这也太异想天开了8，数据是别人构造的又不是你构造的。

**Comment by ostreamBaba** [comment]
数据是别人构造不是你构造的。如果他告诉你长度这题就没意义了。

**Comment by dk-lockdown** [comment]
> 有环的东西还能知道长度?? 想知道长度你还不得要先知道环的入口在哪里，还是得利用快慢指针模拟一遍。
> 这也太异想天开了8，数据是别人构造的又不是你构造的。

往链表加element的时候我能不能记长度，环是怎么产生的？凭空产生的吗？删除element的时候能不能减一个长度，删除element的时候是不是要调整previous、next指针，调整错了得不得造成环

**Comment by crossoverJie** [comment]
@ostreamBaba

是的，一开始我也纳闷一个环怎么知道长度。

想法是可以的，所以让 @dk-lockdown 提一个 `PR`，估计在真正撸码的时候会发现没那么容易。

**Comment by dk-lockdown** [comment]
> 数据是别人构造不是你构造的。如果他告诉你长度这题就没意义了。

出题要严谨啊，问你链表是否有环？正常的链表结构不都记录了长度的？光从字面你能看出这个链表就是代码里写的结构？

**Comment by crossoverJie** [comment]
![](https://ws1.sinaimg.cn/large/006tNbRwly1fw235amki2j30yc0iggnp.jpg)

@dk-lockdown 题目其实是根据 [LeetCode](https://leetcode.com/problems/linked-list-cycle/description/) 过来的。

一般这种题都是给你一个链表，里边并不会有长度字段。

当然这个思路是可以的。

**Comment by crossoverJie** [comment]
> > 数据是别人构造不是你构造的。如果他告诉你长度这题就没意义了。
> 
> 出题要严谨啊，问你链表是否有环？正常的链表结构不都记录了长度的？光从字面你能看出这个链表就是代码里写的结构？

我标题没有表述清楚。

但既然是算法题那一般是最基本的数据结构，如果保存了长度那不如直接存一个是否有环的标记。

**Comment by dk-lockdown** [comment]
> > > 数据是别人构造不是你构造的。如果他告诉你长度这题就没意义了。
> > 
> > 
> > 出题要严谨啊，问你链表是否有环？正常的链表结构不都记录了长度的？光从字面你能看出这个链表就是代码里写的结构？
> 
> 我标题没有表述清楚。
> 
> 但既然是算法题那一般是最基本的数据结构，如果保存了长度那不如直接存一个是否有环的标记。

好些人都在读你这个博客，你要是能把LeetCode这个代码粘贴过去一并作为题目就不会有歧义，有的面试官看了你的博客直接就拿你的问题去问面试者，他们也许并没有真正去想问题

**Comment by crossoverJie** [comment]
> > > > 数据是别人构造不是你构造的。如果他告诉你长度这题就没意义了。
> > > 
> > > 
> > > 出题要严谨啊，问你链表是否有环？正常的链表结构不都记录了长度的？光从字面你能看出这个链表就是代码里写的结构？
> > 
> > 
> > 我标题没有表述清楚。
> > 但既然是算法题那一般是最基本的数据结构，如果保存了长度那不如直接存一个是否有环的标记。
> 
> 好些人都在读你这个博客，你要是能把LeetCode这个代码粘贴过去一并作为题目就不会有歧义，有的面试官看了你的博客直接就拿你的问题去问面试者，他们也许并没有真正去想问题

https://github.com/crossoverJie/JCSprout/blob/27240fade644d815b11ca399e51a4c33adc429c3/src/main/java/com/crossoverjie/algorithm/LinkLoop.java#L13-L25

其实源码里已经限制了基本的数据结构。

不过并不建议面试官通过该 `repo` 来面试，这些只是应当掌握的知识点。

招聘还是要根据自己项目、组织结构的需求来筛选候选人。
