### ISSUE TITLE
关于红包算法的小疑问 

### ISSUE THREAD

**Issue by Eugene1024** [crossoverJie/JCSprout#112]
https://github.com/crossoverJie/JCSprout/blob/master/src/main/java/com/crossoverjie/red/RedPacket.java#L70-L72

为什么需要 这段代码
初始的时候minMoney =1；minMoney ==maxMoney的时候，肯定是最后一个红包了，感觉不需要这段代码
自己写代码的时候想不到实际场景，请LZ指点一二

**Comment by crossoverJie** [comment]
@Eugene1024 是的，没啥作用，应该是我写的时候随手的一个判断，没有做单测覆盖率的测试。

**Comment by shaaoteiman** [comment]
randomRedPacket这个方法在计算剩余红包金额的时候极易出现死循环，最终报出stackoverfolw

**Comment by crossoverJie** [comment]
@shaaoteiman 

应该是递归过多，可以描述下具体场景。

**Comment by shaaoteiman** [comment]
List<Integer> redPackets = redPacket.splitRedPacket(40000, 2);
参数传入40000,2；
测试多次均发生异常，原因就是最后一个红包金额过大，发生多次递归导致
Exception in thread "main" java.lang.StackOverflowError

**Comment by crossoverJie** [comment]
@shaaoteiman 

已经修复，由于默认设置了最小红包为 20000，40000 两个人分肯定会出现分配错误。

现已加了判断及提示，最小红包调大即可。

**Comment by shaaoteiman** [comment]
你好，最新代码测试，还是使用数据40000, 2
结果为：
请调大最小红包金额` MAX_MONEY=[20000]
[]
0

应该不是我们想要的结果吧

**Comment by crossoverJie** [comment]
@shaaoteiman 

> 你好，最新代码测试，还是使用数据40000, 2
> 结果为：
> 请调大最小红包金额` MAX_MONEY=[20000]
> []
> 0
> 
> 应该不是我们想要的结果吧

所以这是需要你调大这个  `MAX_MONEY`。

**Comment by TobyPang** [comment]
红包算法bug 递归栈溢出
如下代码有问题
 //在 minMoney到maxMoney 生成一个随机红包
 int redPacket = (int) (Math.random() * (maxMoney - minMoney) + minMoney);

例如当maxMoney=100 minMoney=99 期望是随机[minMoney,maxMoney ]结果是[minMoney,maxMoney )只能是99 导致递归栈溢出

建议randomRedPacket添加校验，提高极端情况的效率
       //剩余金额只能分成最大，不需随机
        if(totalMoney == MAX_MONEY*count){
            return MAX_MONEY;
        }

        //剩余金额只能分成最小，不需随机
        if(totalMoney == MIN_MONEY*count){
            return MIN_MONEY;
        }
