### ISSUE TITLE
交叉打印奇偶数程序卡住

### ISSUE THREAD

**Issue by rainj2013** [crossoverJie/JCSprout#115]
### 重现步骤
JCSprout/src/main/java/com/crossoverjie/actual/TwoThread.java
这个交叉打印奇偶数的程序，取消防止线程空转的Thread.sleep(10)，为了加大重现概率，适当调大打印上限（while (number.start <= 100) {改成while (number.start <= 100000) ）
### 预期结果
正常交叉打印奇偶数
### 实际结果
打印途中卡住
### 其他相关信息
如果将判断条件（private boolean flag = false）加上volatile修饰，则无论是否加上线程休眠，都不会卡死。理论上锁应该也有可见性和顺序性的效果，为何加上volatile的效果会不同？

**Comment by rainj2013** [comment]
附上可以导致卡住的程序代码

`
import java.util.concurrent.locks.Lock;
import java.util.concurrent.locks.ReentrantLock;

/**
 * Function: 两个线程交替执行打印 1~100
 *
 * lock 版
 *
 * @author crossoverJie
 *         Date: 11/02/2018 10:04
 * @since JDK 1.8
 */
public class TwoThread {

    private int start = 1;

    /**
     * 保证内存可见性
     * 其实用锁了之后也可以保证可见性 这里用不用 volatile 都一样
     */
    private boolean flag = false;

    /**
     * 重入锁
     */
    private final static Lock LOCK = new ReentrantLock();

    public static void main(String[] args) {
        TwoThread twoThread = new TwoThread();

        Thread t1 = new Thread(new OuNum(twoThread));
        t1.setName("t1");


        Thread t2 = new Thread(new JiNum(twoThread));
        t2.setName("t2");

        t1.start();
        t2.start();
    }

    /**
     * 偶数线程
     */
    public static class OuNum implements Runnable {

        private TwoThread number;

        public OuNum(TwoThread number) {
            this.number = number;
        }

        @Override
        public void run() {
            while (number.start <= 100) {

                if (number.flag) {
                    try {
                        LOCK.lock();
                        System.out.println(Thread.currentThread().getName() + "+-+" + number.start);
                        number.start++;
                        number.flag = false;


                    } finally {
                        LOCK.unlock();
                    }
                } /*else {
                    try {
                        //防止线程空转
                        Thread.sleep(10);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                }*/
            }
        }
    }

    /**
     * 奇数线程
     */
    public static class JiNum implements Runnable {

        private TwoThread number;

        public JiNum(TwoThread number) {
            this.number = number;
        }

        @Override
        public void run() {
            while (number.start <= 100) {

                if (!number.flag) {
                    try {
                        LOCK.lock();
                        System.out.println(Thread.currentThread().getName() + "+-+" + number.start);
                        number.start++;
                        number.flag = true;


                    } finally {
                        LOCK.unlock();
                    }
                } /*else {
                    try {
                        //防止线程空转
                        Thread.sleep(10);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                }*/
            }
        }
    }
}`

**Comment by crossoverJie** [comment]
@rainj2013 

https://github.com/crossoverJie/JCSprout/issues/47#issuecomment-402128026

和这个 issue 是类似的。

> 注释描述有误，已经修改。
