### ISSUE TITLE
SQL优化中的“负向查询不能使用索引”,实际是能使用索引的

### ISSUE THREAD

**Issue by pigercc** [crossoverJie/JCSprout#124]
#### Mysql版本
5.5.60-MariaDB MariaDB Server
### 预期结果
不走索引
#### 实际结果
走了索引
ariaDB [futu]> explain select * from tb_test_big_data where name not in ('sf') limit 1;
+------+-------------+------------------+-------+--------------------+--------------------+---------+------+---------+-----------------------+
| id   | select_type | table            | type  | possible_keys      | key                | key_len | ref  | rows    | Extra                 |
+------+-------------+------------------+-------+--------------------+--------------------+---------+------+---------+-----------------------+
|    1 | SIMPLE      | tb_test_big_data | range | ind__test_big_data | ind__test_big_data | 303     | NULL | 6634516 | Using index condition |
+------+-------------+------------------+-------+--------------------+--------------------+---------+------+---------+-----------------------+
1 row in set (0.00 sec)

**Comment by crossoverJie** [comment]
@pigercc 

请使用 `InnoDB` 进行测试；

`version_id` 为索引字段。

 > 正向查询

![image](https://user-images.githubusercontent.com/15684156/48362778-5f8d6e80-e6df-11e8-8744-9abfd93b8d0a.png)

**命中索引**

> 负向查询

![image](https://user-images.githubusercontent.com/15684156/48362834-83e94b00-e6df-11e8-885b-b504cefa153a.png)

**进行全部扫描。**

**Comment by pigercc** [comment]
![image](https://user-images.githubusercontent.com/19647862/48382583-a0f03f00-e71c-11e8-893f-4dfb348d95c5.png)
mysql自己会选择最优的检索方式,这里是不确定的
https://segmentfault.com/q/1010000009426506
https://www.jianshu.com/p/20361fe96f0a

**Comment by crossoverJie** [comment]
@pigercc 

>  但是如果业务数据严重不均的字段加了索引的话是不一定失效的 mysql自己会做判断 并不是绝对判定不使用索引 比如表A性别列有男10000条女20条，当sex!=’男‘是可以使用索引的 同样的如果你sex='男'反而不会使用索引 mysql自己会选择最优的检索方式

看了那个链接。结论没问题，但有一个很重要的前提忘了。

**禁止在区分度不高的字段上加索引** 所以性别是不推荐加索引的。

基于这个标准加了索引的字段都是区分度高的情况下，那么也就 `MySQL` 自己判断自然会在 `not in` 时候不走索引。
