### ISSUE TITLE
有关于设计模式方面的吗？比如枚举实现单例模式等

### ISSUE THREAD

**Issue by oceanhaiyang** [crossoverJie/JCSprout#141]
**在提交issue之前请回答以下问题，谢谢!**

> 建议首先查看是否已经有类似的 Issues (提交时可删除该提示)

### 其他相关信息

**Comment by crossoverJie** [comment]
https://mp.weixin.qq.com/s/2UYXNzgTCEZdEfuGIbcczA


小灰的这篇讲的比较清楚了。
