### ISSUE TITLE
代码优化建议

### ISSUE THREAD

**Issue by honwhy** [crossoverJie/JCSprout#152]
Spring AOP一章中的clazzTest方法，优化建议，
由原来的的
```java
byte[] proxyClassFile = ProxyGenerator.generateProxyClass(
                "$Proxy1", new Class[]{ISubject.class}, 1);
```
改为
```java
byte[] proxyClassFile = ProxyGenerator.generateProxyClass(
                "$Proxy1", new Class[]{ISubject.class}, Modifier.PUBLIC | Modifier.FINAL);
```
参考实现来自：*java.lang.reflect.Proxy.ProxyClassFactory*

且，
```java
public static final int PUBLIC           = 0x00000001;
public static final int FINAL            = 0x00000010;
```
两个属性或运算的结果并不是*1*。

**Comment by crossoverJie** [comment]
@honwhy 

我查了下资料，发现对于 `accessFlags` 的官方注释为 `access flags of the proxy class`

也没有解释不同值之间的差异，换为 `Modifier.PUBLIC | Modifier.FINAL` 有什么区别嘛？

**Comment by honwhy** [comment]
@crossoverJie 参考下 javadoc ![java.lang.reflect.Proxy](https://docs.oracle.com/javase/7/docs/api/java/lang/reflect/Proxy.html)
一个Proxy类有以下的属性，
>Proxy classes are public, final, and not abstract
如果不是final的话，那么Proxy可能被继承，方法被覆盖； 这里final是重要的；

**Comment by crossoverJie** [comment]
@honwhy 图片裂了。

其实换为 `Modifier.PUBLIC | Modifier.FINAL`的区别。
