### ISSUE TITLE
关于 jdk1.8 HashMap treeifyBin 树形化场景的疑问

### ISSUE THREAD

**Issue by AaronYSJ** [crossoverJie/JCSprout#157]
HashMap 章节提到
> 在 JDK1.8 中对 HashMap 进行了优化： 当 hash 碰撞之后写入链表的长度超过了阈值(默认为8)，链表将会转换为红黑树

最近在看源码的时候，模拟了一下 hashmap hash 碰撞的场景，直接向一个空的 hashmap 中，连续 put 了12个相同 hashcode 的 key, 发现并没有立即树形化成红黑树，到第11个才发生。

treeifyBin 函数的第二行就有相关判断语句
```java
final void treeifyBin(Node<K,V>[] tab, int hash) {
        int n, index; Node<K,V> e;
        if (tab == null || (n = tab.length) < MIN_TREEIFY_CAPACITY)
            resize();
        else // 树形化代码
       .....
}
```
即，tab 的长度要大于这个 MIN_TREEIFY_CAPACITY 值才会进行红黑树转化。
```java
   /**
     * The smallest table capacity for which bins may be treeified.
     * (Otherwise the table is resized if too many nodes in a bin.)
     * Should be at least 4 * TREEIFY_THRESHOLD to avoid conflicts
     * between resizing and treeification thresholds.
     */
    static final int MIN_TREEIFY_CAPACITY = 64;
```

这个碰撞后，链表的长度超过了默认阈值8也不是立马就树形化，还要判断下 table 的 length 是否大于64，这样链表才会转换为红黑树。

考虑改为

在 JDK1.8 中对 HashMap 进行了优化： 当 hash 碰撞之后写入链表的长度超过了阈值(默认为8)并且 table 的长度不小于64，链表将会转换为红黑树

**Comment by Alvin4Jay** [comment]
是的，先扩容解决

AaronYE <notifications@github.com>于2019年4月3日 周三21:05写道：

**Comment by crossoverJie** [comment]
@AaronYSJ 可以提个 PR 完善这个描述。
