### ISSUE TITLE
希望增加gitbook版本

### ISSUE THREAD

**Issue by Jadyli** [crossoverJie/JCSprout#39]

**Comment by crossoverJie** [comment]
@Jadyli 

感谢关注。

好建议，研究下。弄好了通知大家。

**Comment by crossoverJie** [comment]
@Jadyli 

https://crossoverjie.top/JCSprout/#/

换了一个文档，更加美观和直接。

**Comment by Jadyli** [comment]
哇，好漂亮，是怎么做的啊？

**Comment by crossoverJie** [comment]
@Jadyli 

https://docsify.js.org/#/
