### ISSUE TITLE
LinkedList中的关于二分法查找的问题

### ISSUE THREAD

**Issue by destinym** [crossoverJie/JCSprout#61]
文章中写道
【由此可以看出是使用二分查找来看 index 离 size 中间距离来判断是从头结点正序查还是从尾节点倒序查】
二分法查找的时间复杂度是logn,是个递归的过程。
但是，看代码中，本身数据结构是双向链表，只能从头往后，或者从后往前访问，所以，这个应该是指计算出来index属于上半区还是下半区，上半区就从头往后，  下半区就从后往前。  时间复杂度应该是n的。

**Comment by crossoverJie** [comment]
@destinym 是的 见 #45

**Comment by destinym** [comment]
我还是觉得不太合适，会让一些初学者引起误解。
1 二分法查找一般是针对值进行查找。
2 二分法一般会先把队列排序，然后才能进行查找。
这个其实是对index的一个查找。
我觉得不如改成，（这个段代码作用就是从头部遍历，或者从尾部遍历，利用了双向链表的特性，通过空间换取时间）

**Comment by crossoverJie** [comment]
@destinym 嗯，我一时也没找到太好的表达方式。

 可以提个 PR。
