### ISSUE TITLE
类加载器那个，什么情况下父类加载器返回不能加载，然后子类自己去加载呢

### ISSUE THREAD

**Issue by kennywgx** [crossoverJie/JCSprout#89]
是抽象类就会返回不能加载吗？如果父类能加载，那子类拿到父类加载的结果之后又要做什么？

**Comment by crossoverJie** [comment]
@kennywgx 

通常是自定义的类父类不会加载，比如你定义一个 `Person.java` ，但如果你定义了一个 `java.lang.Integer` 那肯定是父类优先给你加载了。

**Comment by whdalive** [comment]
@kennywgx
换个角度解释，默认下 BootStrapClassLoader、ExtClassLoader、AppClassLoader都是加载指定路径下的jar包，比如AppClassLoader加载的是当前 classpath 下的类，核心在于加载的资源路径。
如果此时你想加载磁盘某个位置或者网络中的某个类，那么你就需要自己定义一个ClassLoader 来加载特定路径。
以上，粗略理解，有误还请指出。

**Comment by devpage** [comment]
我来回答一下。在你项目运行过程中，当需要某个类的时候，恰好在当前cladspath下 你当前jvm中的各类classloader都拿不到某个类的时，你就需要自己搞一个classloader来做娄底方案了，听懂了没有
