### ISSUE TITLE
 Disruptor发生内存溢出问题讨论

### ISSUE THREAD

**Issue by sosojustdo** [crossoverJie/JCSprout#94]
你好：
       阅读了作者您的博客：https://crossoverjie.top/2018/08/29/java-senior/OOM-Disruptor/ 之后，自己也动手写了下单元测试，oom问题无疑，但是对于博客中有一段话存在不解：“我设置队列大小为 8 ，从 0~9 往里面写 10 条数据，当写到 8 的时候就会把之前 0 的位置覆盖掉，后面的以此类推（类似于 HashMap 的取模定位）。”；而我的单侧中，event数大于buffersize的时候，produce.publish方法回阻塞，我的单测地址：
https://github.com/sosojustdo/disruptor-learning/commit/fb7461278149b2b43061a46811d15a579ef63dbd

**Comment by crossoverJie** [comment]
@sosojustdo 

嗯，其实我想表达的意思是：

> Disruptor 环形队列里的数据只有等到下一轮数据覆盖掉才会被回收。

阻塞的情况肯定是数据没有被消费导致生产者阻塞了，这是一个阻塞队列的基本功能。

**Comment by sosojustdo** [comment]
@crossoverJie 
阻塞队列要是满了，入队列不是会阻塞吗？“Disruptor 环形队列里的数据只有等到下一轮数据覆盖掉才会被回收。”这句话“下一轮数据覆盖掉” 意思是队列满了还能入队列，典型的场景：生产速度大于消费速度的时候会出现上面情况？，岂不是违背了阻塞队列初衷。disruptor队列刚使用，不太熟悉，望您指教，谢谢。。

**Comment by crossoverJie** [comment]
@sosojustdo 

> "下一轮数据覆盖掉"

忘了说这个前提了，前提是有消费之后才会覆盖。

比如我文章里面模拟的 8 个坑的队列。

主线程写入 10 条数据，消费线程去消费，肯定边消费边生产的。

如下图所示：

![](https://ws4.sinaimg.cn/large/006tNbRwly1fuxv1mb9laj31120gs7bo.jpg)

> 典型的场景：生产速度大于消费速度的时候会出现上面情况？

这样的场景肯定会导致生产者阻塞。

我在这里模拟消费比较慢的场景。

https://github.com/crossoverJie/JCSprout/blob/397ee3763e12279fd83d26d02da20955d5bcc7cf/src/main/java/com/crossoverjie/disruptor/LongEventHandler.java#L17-L19

通过日志会发现生产者很快把 8 个消息写进入，到第 9 个的时候就阻塞了等到消费一条数据之后才会继续生产数据。

![](https://ws1.sinaimg.cn/large/006tNbRwly1fuxv9lvvkxj31by0jo47w.jpg)

dump 线程也会发现 main 线程作为生产者确实是 waiting 状态。

![](https://ws3.sinaimg.cn/large/006tNbRwly1fuxvapulmqj31kw0apn1a.jpg)
