### ISSUE TITLE
关于SQL优化中的"创建索引中关于性别字段创建索引"的疑问

### ISSUE THREAD

**Issue by G-bug** [crossoverJie/JCSprout#97]
### SQL优化数据区分不明显的不建议创建索引
>如 user 表中的性别字段，可以明显区分的才建议创建索引，如身份证等字段。

#### 因为看到MySQL技术内幕（第四版）中同样例子，感觉有些出入，所以问一下。

![image](https://user-images.githubusercontent.com/17786381/45219381-4c27e680-b2dd-11e8-93fd-ec0db91e6242.png)

菜鸟一枚，如有不对还望悉心指教:blush:

**Comment by crossoverJie** [comment]
@G-bug 问题是什么呢？我的意思和文中一致，就是不建议对性别字段创建索引。

**Comment by G-bug** [comment]
感谢您的回复。
了解了，是我弄错了，抱歉:sweat_smile:
